id: P003292
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4470
  title: དྲང་ངེས་ལེགས་བཤད་སྙིང་པོ
  author: ''
  volumes:
    d2b8415c029f4f6c8592928fa843f0ef:
      image_group_id: I1KG4495
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
